name: Deploy static HTML site to Azure Web App - DivineTestt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5502E9D82C9F420C9855D8C025C49BD6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_20A71539565C4020B4DDE03EAB3A56BD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A3C720F1280F42D6A1EF935DAC270D90 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'DivineTestt'
          slot-name: 'Production'
          package: .
